POST http://localhost:3000/flowers/create HTTP/1.1
Content-Type: application/json

{
	"name": "1",
	"price": 2
}

###

GET http://localhost:3000/flowers/

###

DELETE http://localhost:3000/flowers/624d65e4999c5954c9e9e4b6 HTTP/1.1

###

PUT http://localhost:3000/flowers/624c57f5cb85cf48053a3e9e HTTP/1.1
Content-Type: application/json

{
	"name": "new name",
	"price": 2
}

###

POST http://localhost:3000/user/create HTTP/1.1
Content-Type: application/json

{
	"name": "olha",
	"email": "olha2@gmail.com",
	"admin": true,
	"flowers": "k"
}
###

###
GET http://localhost:3000/user/


###
DELETE http://localhost:3000/user/
###

PATCH http://localhost:3000/user/62542185ff4aab78dc7febcf/flowers/624d6650999c5954c9e9e4be HTTP/1.1
Content-Type: application/json

{
	"name": "olha",
	"email": "olha2@gmail.com",
	"admin": true,
	"flowers": "k"
}
###


