POST http://localhost:3000/flowers/create HTTP/1.1
Content-Type: application/json

{
	"name": "Tulip5",
	"price": 2,
	"instock": 4
}

###

GET http://localhost:3000/flowers/


###

DELETE http://localhost:3000/flowers/624d65e4999c5954c9e9e4b6 HTTP/1.1

###

PUT http://localhost:3000/flowers/624c57f5cb85cf48053a3e9e HTTP/1.1
Content-Type: application/json

{
	"name": "new name",
	"price": 2
}

###

POST http://localhost:3000/user/create HTTP/1.1
Content-Type: application/json

{
	"name": "olha",
	"email": "olha2@gmail.com",
	"admin": true,
	"flowers": "k"
}
###
POST http://localhost:3000/user/create HTTP/1.1
Content-Type: application/json

{
	"name": "olha",
	"email": "olha7@gmail.com",
	"admin": false,
	"password": "helloword"
}

###
POST http://localhost:3000/user/login HTTP/1.1
Content-Type: application/json

{
	"email": "olha7@gmail.com",
	"password": "helloword"
}

###
GET http://localhost:3000/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY2ZWIzMWE0M2VlYzY0YzdlYmZiNjYiLCJlbWFpbCI6Im9saGE3QGdtYWlsLmNvbSIsImlhdCI6MTY1MDk2ODQ4NX0.0yIsQ62IOdaAroErKWgByGUP-j_3HMHEaMS2jWYTQoE

###
DELETE http://localhost:3000/user/
###

PATCH http://localhost:3000/user/62542185ff4aab78dc7febcf/flowers/624d6650999c5954c9e9e4be HTTP/1.1
Content-Type: application/json

{
	"name": "olha",
	"email": "olha2@gmail.com",
	"admin": true,
	"flowers": "k"
}
###
